theme: minima
title: About Me!
author: Izel Abreu-Feliciano
email: izelabreu03@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Site to write about me and create a portfolio of all my work

# social links
instagram_username: xoizel # DO NOT include the @ character, or else the build will fail!
github_username:  izelab # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
